"$schema" = "https://raw.githubusercontent.com/jsonresume/resume-schema/v1.0.0/schema.json"

[basics]
email = "pbsds@hotmail.com"
image = "./me.jpg"
label = "Programmer, Researcher"
name = "Peder Bergebakken Sundt"
#phone = "(+47) "
summary = """\
    Peder is a Norwegian pythonista with an early start and wide interest in computing, including machine learning, 3D graphics, networking, reverse engineering, systems development, reproducible package management and builds, and declarative system configuration and deployment. \
    He is currently researching neural fields at NTNU, and regularly submits tweaks and fixes to various open source projects. \
"""
url = "https://pbsds.net"

  [basics.location]
  #address = ""
  #postalCode = ""
  city = "Trondheim"
  region = "Trøndelag"
  countryCode = "NO"

  [[basics.profiles]]
  network = "GitHub"
  url = "https://github.com/pbsds"
  username = "pbsds"

  [[basics.profiles]]
  network = "LinkedIn"
  url = "https://www.linkedin.com/in/peder-bergebakken-sundt-181a4b94/"
  username = "Peder B. Sundt"

  # [[basics.profiles]]
  # network = "Twitter"
  # url = "https://twitter.com/pederpbsds"
  # username = "pederpbsds"

  [[basics.profiles]]
  network = "Mastodon"
  url = "https://snabelen.no/@pbsds"
  username = "@pbsds@snabelen.no"

  [[basics.profiles]]
  network = "ORCID"
  url = "https://orcid.org/0009-0008-7141-9489"
  username = "ORCID"

  [[basics.profiles]]
  network = "NTNU Open"
  url = "https://ntnuopen.ntnu.no/ntnu-xmlui/browse?value=Sundt,%20Peder%20Bergebakken&type=author"
  username = "NTNU Open"


[[work]]
name = "Norwegian University of Science and Technology (NTNU)"
# url = "https://www.ntnu.edu/"
url = "https://www.ntnu.edu/employees/peder.b.sundt"
position = "PhD Candidate"
description = "Researcher"
location = "Trondheim, NO"
startDate = "2021-08"
# endDate = "2025-09"
highlights = [
    "Conceptualized, researched and published 3 papers on 3D neural ray intersection fields (third paper pending).",
    "Worked as Assignment Coordinator, teaching introductory and advanced graphics and visualization using OpenGL (TDT4195/TDT4230).",
]
summary = "The Norwegian University of Science and Technology (NTNU) is a public research university in Norway and the largest in terms of enrollment."


#[[work]]
#name = "NDC TechTown"
#url = "https://web.archive.org/web/20231016205130/https://ndctechtown.com/speakers/peder-bergebakken-sundt"
#position = "Workshop Holder"
#description = "Speaker"
#location = "Kongsberg, NO"
##startDate = "2022-09"
##endDate = "2023-09"
## https://web.archive.org/web/20231016205130/https://ndctechtown.com/speakers/peder-bergebakken-sundt
#highlights = [
#  "Python Proficiency - a 2-day course (2022, 2023)",
#]


[[work]]
name = "Uninett"
url = "https://uninett.no"
position = "Summer Intern, then part-time Systems Developer"
description = "Internship"
location = "Trondheim, NO"
startDate = "2019-06"
endDate = "2020-08"
highlights = [
  "Working with Eduroam and EAP/RADIUS client certificate authentication.",
  "Python, FreeBSD, Window and .NET development.",
]
summary = "Uninett is the company responsible for Norway's National Research and Education Network. They develops and operate the national research network in Norway."

[[work]]
name = "Arm Norway"
url = "https://careers.arm.com/norway-trondheim-office"
position = "Summer Intern, CI"
description = "Internship"
location = "Trondheim, NO"
startDate = "2018-06"
endDate = "2018-08"
highlights = [
  "Set up internal tooling and CI flows for the hardware team to run on their HPC infrastructure.",
]
summary = "Arm Norway works with Arm' Cambridge and Austin design centres to develop graphics processing units for OpenGL, OpenGL ES, DirectX and Vulkan three-dimensional rendering, with emphasis on low electric power consumption, suitable for use in portable devices like mobile phones. Their products are marketed under the Mali brand."

[[work]]
name = "Telenor Digital"
url = "https://telenordigital.com"
position = "Summer Intern, Web development"
description = "Internship"
location = "Trondheim, NO"
startDate = "2017-06"
endDate = "2017-08"
highlights = [
  "Java web development using their SSO solution and payment solutions.",
]
summary = "Telenor Digital developed a Payment portal and SSO system used in Telenor."


[[volunteer]]
startDate = "2015-09-05"
endDate = "2021-10"
organization = "Programvareverkstedet (PVV)"
url = "http://pvv.ntnu.no/"
position = "Board Member, Chair Person and Operations Coordinator"
summary = "A Student organisation for those with interest in computers"
highlights = [
  "Board member from 2015 to 2018",
  "Chair person from 2016 to 2017",
  "Operations coordinator for 6 years",
]


[[education]]
studyType = "Masters"
area = "Computer Science"
courses = [
  "TDT4900 - Computer Science, Master's Thesis",
  "TDT4295 - Computer Design Project",
  "TDT4230 - Graphics & Visualization",
]
startDate = "2015-08"
endDate = "2021-06"
institution = "Norwegian University of Science and Technology (NTNU)"
score = "A on thesis, B overall"
url = "https://www.ntnu.edu/"
# highlights = [ "Worked as Teaching Assistant in C++ (TDT4102) Spring 2017, 2018 and 2019." ]
# summary = "Started in telematics, switched to algorithms and graphics, wrote thesis on machine learning."

[[awards]]
awarder = "Eurographics Symposium on 3D Object Retrieval 2023 (3DOR'23)"
date = "2023-09-01"
title = "Best Paper Award"
summary = "MARF: The Medial Atom Ray Field Object Representation"

[[publications]]
name = "Towards multi-view consistency in neural ray fields using parametric medial surfaces"
publisher = "Computers & Graphics Vol 123"
releaseDate = "2024-10"
summary = "A novel neural ray intersection field which improves multi-view consistency by limiting the degrees-of-freedom in a dual shape reconstruction domain."
url = "https://doi.org/10.1016/j.cag.2024.103991"

[[publications]]
name = "MARF: The Medial Atom Ray Field Object Representation"
publisher = "Computers & Graphics Vol 115"
releaseDate = "2023-10"
summary = "A novel neural ray-based 3D shape representation enabling order of magnitude faster differentiable surface rendering."
url = "https://doi.org/10.1016/j.cag.2023.06.032"


# https://web.archive.org/web/20231016205130/https://ndctechtown.com/speakers/peder-bergebakken-sundt

# levels: beginner, intermediate, advanced, master

[[skills]]
name = "Machine learning - 3D Neural Fields"
keywords = [ "Python", "PyTorch", "COLMAP", "Trimesh" ]
level = "Master"

[[skills]]
name = "3D Graphics"
keywords = [ "C++", "Rust", "OpenGL", "GLSL" ]
level = "Advanced"

[[skills]]
name = "System Administration and Software Deployment"
keywords = [ "Nix/NixOS", "Arch", "Debian", "FreeBSD", "SaltStack", "Docker", "VMWare", "ZFS" ]
level = "Advanced"

[[skills]]
name = "Software Development"
keywords = [ "Python", "C++", "C#", "Java" ]
level = "Advanced"

[[skills]]
name = "Web Development"
keywords = [ "Nginx", "FastAPI", "Jinja2", "OpenAPI", "HTML", "CSS", "Bootstrap", "Tailwind", "PostgreSQL", "TimescaleDB" ]
level = "Intermediate"

[[skills]]
name = "Teaching / Hosting Workshops"
keywords = [ "TDT4230", "TDT4102", "NDC TechTown 2022/2023", "Sintef 2018/2020" ]
level = "intermediate"

[[skills]]
name = "Live Audio"
keywords = [ "RørosLyd", "Midas Pro" ]
level = "Intermediate"

[[skills]]
name = "Diagrams-as-code"
keywords = [ "GraphViz", "LaTeX / TikZ", "Typst / CeTZ", "Mermaid / Gantt" ]
level = "intermediate"

[[skills]]
name = "Hardware Design"
keywords = [ "Yosys", "NextPNR", "Vivado", "Chisel3", "Amaranth" ]
level = "Beginner"

# [[skills]]
# name = "Game Development"
# keywords = [ "Pygame", "Panda3D", "OpenGL", "Game Maker", "Unity", "OpenXR" ]
# level = "Beginner"


[[languages]]
language = "Norwegian"
fluency = "Native speaker"

[[languages]]
language = "English"
fluency = "Fluent"

[[interests]]
name = "Free Software"
keywords = [ "Linux", "Software Freedom", "Python", "Nix", "FreeBSD", "ZFS" ]

[[interests]]
name = "IRL"
keywords = [ "Board games", "Bouldering", "Kayaking", "Movies", "Craft Beer", "Cabin trips" ]

#[[references]]
#name = "Erlich Bachman"
#reference = "It is my pleasure to recommend Richard, his performance working as a consultant for Main St. Company proved that he will be a valuable addition to any company."

[[projects]]
name = "NixOS/nixpkgs"
entity = "NixOS Foundation"
url = "https://github.com/NixOS/nixpkgs"
description = "Has authored, maintained, and reviewed many contributions to NixOS/nixpkgs since 2022."
# keywords = ["Operating systems", "Package Management"]
roles = ["Code Reviewer", "Developer", "Maintainer"]
type = "maintainer"
highlights = [
    "Joined in 2022, received commit access in 2023",
    "6000+ commits, 72% merge commits",
]
#startDate = "2016-08-24"
#endDate = "2016-08-24"
#highlights = [
#  "Won award at AIHacks 2016",
#  "Built by all women team of newbie programmers",
#  "Using modern technologies such as GoogleMaps, Chrome Extension and Javascript"
#]

[meta]
canonical = "https://raw.githubusercontent.com/jsonresume/resume-schema/master/resume.json"
lastModified = "2017-12-24T15:53:00"
version = "v1.0.0"
# Set default theme when fetching through
# https://registry.jsonresume.org/<github-user-name>, see themes
# here: https://jsonresume.org/themes/
